### ISSUE TITLE
Methylation Probabilitiy

### ISSUE THREAD

**Issue by olaraym** [nebiolabs/EM-seq#8]
Thanks @bwlang for the response earlier. I am actually working with the genome of sugar beet and I am new to these kinds of analyses. I don't know if the lambda and pUC19 controls will work in this instance and If they will, can you please explain how to implement their usage in my work?

Someone suggested I use the chloroplast genome as a negative control since it's fully unmethylated but honestly, I have no idea how to go about that. I will be glad if you can shed more light on this supposed "control" implementation.

**Comment by bwlang** [comment]
The pUC19 and lambda controls are added to your sample (beet in this case) so they are always available if you add them as the manual suggests.  I recommend supplementing the genome you are working with by appending the methylation_controls.fa in this repository to the reference so that you can evaluate them by simply looking at  methylation for those "chromosomes". I don't know the methylation state of plastid DNA in plants, but I'd be more confident using controls with defined methylation state. 

Github issues are intended as a place to suggest improvement to the analysis methods.  For more specific questions about EM-seq it's best to contact NEB tech support (info at neb.com).
